name: forecast-mae
phase: pretrain

target:
  _target_: src.model.trainer_mae.Trainer
  dim: 128
  historical_steps: 50
  future_steps: 60
  encoder_depth: 4
  decoder_depth: 4
  num_heads: 8
  mlp_ratio: 4.0
  qkv_bias: False
  drop_path: 0.2
  actor_mask_ratio: 0.5
  lane_mask_ratio: 0.5
  loss_weight: [1.0, 1.0, 0.35]
  lr: ${lr}
  weight_decay: ${weight_decay}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
